<?php

namespace App\Services;

use App\Repositories\Gift\GiftRepositoryInterface;
use App\Repositories\Product\ProductRepositoryInterface;
use App\Services\BaseService;
use App\Models\Gift;

class GiftService extends BaseService
{
    protected $repository;
    protected $productRepository;

    public function __construct(GiftRepositoryInterface $repository, ProductRepositoryInterface $productRepository)
    {
        parent::__construct();

        $this->repository = $repository;
        $this->productRepository = $productRepository;
    }

    public function formOptions($model = null): array
    {
        $options                   = parent::formOptions($model); // TODO: Change the autogenerated stub
        $options['products'] = $this->productRepository->getActiveProduct()->pluck('name', 'id')->toArray();

        return $options;
    }

    public function setModel()
    {
        return new Gift();
    }

    public function getDataForScreenList($requestParams) {
        return $this->repository->getByRequest(20, ['product'], $requestParams);
    }

    public function update($id, $attributes)
    {
        $this->repository->update($id, $attributes);
    }
}
