<?php

namespace App\Repositories\File;

use App\Models\File;
use App\Repositories\BaseRepository;

class FileRepository extends BaseRepository implements FileRepositoryInterface
{

    /**
     * @return mixed|\Illuminate\Database\Eloquent\Model
     */
    public function getModel()
    {
        return new File();
    }

    public function getByArrId($arrId, $with = [])
    {
        return parent::getByArrId($arrId, $with); // TODO: Change the autogenerated stub
    }
}
